export const data = [
  {
    id: 1,
    name: "Murilo Mendes",
    years: 20,
    flag: "./assets/brazil.png",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga blanditiis assumenda ab praesentium nihil nulla dicta autem voluptatibus? Ipsa doloribus possimus distinctio vero nostrum soluta aspernatur quia quisquam laudantium et.",
    image: "./assets/murilo.png",
  },
  {
    id: 2,
    name: "Miguel Trindade",
    years: 20,
    flag: "./assets/portugal.jpeg",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga blanditiis assumenda ab praesentium nihil nulla dicta autem voluptatibus? Ipsa doloribus possimus distinctio vero nostrum soluta aspernatur quia quisquam laudantium et.",
    image: "./assets/miguel.png",
  },
  {
    id: 3,
    name: "Sandra Vicente",
    years: 20,
    flag: "./assets/portugal.jpeg",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga blanditiis assumenda ab praesentium nihil nulla dicta autem voluptatibus? Ipsa doloribus possimus distinctio vero nostrum soluta aspernatur quia quisquam laudantium et.",
    image: "./assets/sandra.png",
  },
  {
    id: 4,
    name: "João Tiago",
    years: 20,
    flag: "./assets/portugal.jpeg",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga blanditiis assumenda ab praesentium nihil nulla dicta autem voluptatibus? Ipsa doloribus possimus distinctio vero nostrum soluta aspernatur quia quisquam laudantium et.",
    image: "./assets/joao.png",
  },
  {
    id: 5,
    name: "Patricia Lourenço",
    years: 20,
    flag: "./assets/portugal.jpeg",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga blanditiis assumenda ab praesentium nihil nulla dicta autem voluptatibus? Ipsa doloribus possimus distinctio vero nostrum soluta aspernatur quia quisquam laudantium et.",
    image: "./assets/patricia.png",
  },
  {
    id: 6,
    name: "André Ribeiro",
    years: 20,
    flag: "./assets/portugal.jpeg",
    info: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga blanditiis assumenda ab praesentium nihil nulla dicta autem voluptatibus? Ipsa doloribus possimus distinctio vero nostrum soluta aspernatur quia quisquam laudantium et.",
    image: "./assets/andre.png",
  },
];
